import { StandardRole } from "./career-intelligence-data";

export interface InterviewStage {
  name: string;
  desc: string;
  type: "oa" | "technical" | "system_design" | "managerial" | "hr";
}

export interface VerifiedCompany {
  id: string;
  name: string;
  logo: string;
  industry: string;
  category:
    | "Big Tech / FAANG+"
    | "AI Leaders & Research"
    | "Global Product Unicorns"
    | "FinTech & Payments"
    | "Cloud & DevOps"
    | "Cyber Security"
    | "Gaming & Interactive"
    | "Semiconductor & Hardware"
    | "Indian Product Unicorns"
    | "Enterprise SaaS"
    | "IT Services & Consulting";
  workMode: "Hybrid" | "Remote-friendly" | "On-site";
  scale: string;
  headquarters: string;
  salaryRange: string;
  estimatedPrepMonths: number;
  hiringDifficulty: number; // 1 to 5
  primaryTechnologies: string[];
  typicalRoles: StandardRole[];
  aliases: string[];
  misspellings: string[];
  interviewStages: InterviewStage[];
  topSkillsNeeded: string[];
  relatedCompanyIds: string[];
  mentorCommentary: {
    nova: string;
    athena: string;
    byte: string;
    raven: string;
    atlas: string;
    sage: string;
  };
}

// ---------------------------------------------------------------------------
// VERIFIED COMPANY DIRECTORY (Strict Standardization - No Custom Creation)
// ---------------------------------------------------------------------------
export const VERIFIED_COMPANIES: VerifiedCompany[] = [
  // =========================================================================
  // 1. BIG TECH / FAANG+
  // =========================================================================
  {
    id: "google",
    name: "Google",
    logo: "google",
    industry: "Internet, Cloud & AI",
    category: "Big Tech / FAANG+",
    workMode: "Hybrid",
    scale: "180k+ Employees",
    headquarters: "Mountain View, CA",
    salaryRange: "₹25L–65L",
    estimatedPrepMonths: 8,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Go",
      "C++",
      "Java",
      "Python",
      "TensorFlow",
      "Angular",
      "Flutter",
      "Android",
      "Kubernetes",
      "GCP",
    ],
    typicalRoles: [
      "Software Engineer",
      "Backend Developer",
      "AI Engineer",
      "Machine Learning Engineer",
      "Cloud Engineer",
      "Android Engineer",
    ],
    aliases: [
      "Alphabet",
      "Google AI",
      "DeepMind",
      "Google DeepMind",
      "YouTube",
      "Android",
      "Flutter",
      "Firebase",
      "TensorFlow",
      "Gemini",
      "Chrome",
      "Angular",
      "Go",
      "Golang",
      "Google Cloud",
      "GCP",
      "Maps API",
      "Google Maps",
    ],
    misspellings: ["Gooogle", "Gogle", "Googel", "Ggogle"],
    interviewStages: [
      { name: "Online Assessment", desc: "60–90 min DSA coding on Google Foobar/HackerRank", type: "oa" },
      { name: "Technical Phone Screen", desc: "45 min live DSA coding with a Google Senior SWE", type: "technical" },
      { name: "Onsite Technical (x3)", desc: "Deep Algorithmic problem solving, graphs & trees", type: "technical" },
      { name: "System Design", desc: "High-scale distributed systems architecture", type: "system_design" },
      { name: "Googleyness & Leadership", desc: "Behavioral and collaborative alignment", type: "hr" },
    ],
    topSkillsNeeded: ["Data Structures & Algorithms", "Distributed Systems", "Concurrency", "Time Complexity Optimization"],
    relatedCompanyIds: ["microsoft", "meta", "amazon", "apple", "openai"],
    mentorCommentary: {
      nova: "Google interviews heavily emphasize algorithms and scalable thinking. Daily DSA practice will give you the biggest return.",
      athena: "Master the fundamentals first. Google values conceptual problem-solving and clean mathematical logic more than memorized syntax.",
      byte: "Don't just solve LeetCode. Learn why the solution works under the hood. Future you will thank you.",
      raven: "Google won't lower the bar because you're nervous. Make your time complexity O(N) or O(log N) without hesitation.",
      atlas: "Targeting Google signals top-tier ambition. We'll tailor your resume for Google's automated ATS parsing.",
      sage: "We will structure an 8-month phased curriculum moving from arrays and graphs into Google's favorite dynamic programming topics.",
    },
  },
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "microsoft",
    industry: "Cloud, Enterprise Software & AI",
    category: "Big Tech / FAANG+",
    workMode: "Hybrid",
    scale: "220k+ Employees",
    headquarters: "Redmond, WA",
    salaryRange: "₹20L–55L",
    estimatedPrepMonths: 6,
    hiringDifficulty: 5,
    primaryTechnologies: [
      ".NET",
      "C#",
      "Azure",
      "TypeScript",
      "React",
      "Python",
      "C++",
      "SQL Server",
      "Kubernetes",
    ],
    typicalRoles: [
      "Backend Developer",
      "Software Engineer",
      "Cloud Engineer",
      "Full Stack Engineer",
      "AI Engineer",
    ],
    aliases: [
      "Azure",
      "Microsoft Azure",
      "MSFT",
      "MS",
      "VS Code",
      "Visual Studio Code",
      "Copilot",
      "GitHub Copilot",
      "GitHub",
      "Azure DevOps",
      "Teams",
      "Microsoft Teams",
      "TypeScript",
      "C#",
      ".NET",
      "Windows",
      "Xbox",
      "LinkedIn",
    ],
    misspellings: ["Micorsoft", "Micro soft", "Micosoft", "Msft"],
    interviewStages: [
      { name: "Online Assessment", desc: "Codility assessment with 3 DSA questions", type: "oa" },
      { name: "Technical Round 1", desc: "Data structures, problem solving & clean code modularity", type: "technical" },
      { name: "Technical Round 2", desc: "Low-level object-oriented design and concurrency", type: "technical" },
      { name: "System Design Round", desc: "Microservices design, caching & data schemas", type: "system_design" },
      { name: "AA (As Appropriate) Round", desc: "Director-level architectural & cultural interview", type: "managerial" },
    ],
    topSkillsNeeded: ["C# / Java", ".NET Core or Spring", "Azure Cloud Architecture", "OOP & System Design", "DSA"],
    relatedCompanyIds: ["google", "amazon", "apple", "meta", "atlassian"],
    mentorCommentary: {
      nova: "Microsoft is a fantastic target for Backend and Cloud Engineers. Azure familiarity and clean API design give you huge leverage.",
      athena: "Microsoft evaluates structured engineering and collaborative problem solving. Practice explaining your architectural trade-offs.",
      byte: "Master async/await, memory allocation, and SOLID principles. Microsoft loves clean, maintainable engineering.",
      raven: "Enterprise production requires bulletproof reliability. Know your concurrency boundaries and thread safety inside out.",
      atlas: "Microsoft has phenomenal campus and lateral hiring quotas. Aligning your resume with Azure and .NET yields instant visibility.",
      sage: "A 6-month roadmap prioritizing DSA medium problems alongside a deployed cloud-native project will maximize callback rates.",
    },
  },
  {
    id: "meta",
    name: "Meta",
    logo: "meta",
    industry: "Social Technology, AI & Metaverse",
    category: "Big Tech / FAANG+",
    workMode: "Hybrid",
    scale: "70k+ Employees",
    headquarters: "Menlo Park, CA",
    salaryRange: "₹28L–70L",
    estimatedPrepMonths: 7,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "React",
      "PyTorch",
      "C++",
      "Python",
      "GraphQL",
      "Hack / PHP",
      "Rust",
      "Android",
      "iOS",
    ],
    typicalRoles: [
      "Frontend Developer",
      "Software Engineer",
      "AI Engineer",
      "Machine Learning Engineer",
      "Full Stack Engineer",
    ],
    aliases: [
      "Facebook",
      "FB",
      "Meta Platforms",
      "Instagram",
      "WhatsApp",
      "Threads",
      "Llama",
      "Messenger",
      "Oculus",
      "Meta Quest",
      "PyTorch",
      "React",
      "GraphQL",
      "React Native",
    ],
    misspellings: ["Mata", "Facebok", "Insta", "Whatapp"],
    interviewStages: [
      { name: "Screening Assessment", desc: "Two LeetCode medium/hard questions in 45 minutes", type: "technical" },
      { name: "Coding Onsite (x2)", desc: "Flawless bug-free algorithm implementation under speed", type: "technical" },
      { name: "System Design / Product Architecture", desc: "Designing Newsfeed, Chat, or Distributed Cache", type: "system_design" },
      { name: "Behavioral & Impact", desc: "Demonstrating move fast, autonomy, and ownership", type: "hr" },
    ],
    topSkillsNeeded: ["Lightning-fast DSA Coding", "High-Throughput Distributed Systems", "React / Client UI Architecture", "PyTorch"],
    relatedCompanyIds: ["google", "apple", "netflix", "openai", "stripe"],
    mentorCommentary: {
      nova: "Meta demands rapid, bug-free execution. You have 20 minutes per algorithm on the whiteboard—speed and precision win here.",
      athena: "Meta's culture is built around high autonomy. Be prepared to discuss end-to-end technical leadership in your past projects.",
      byte: "Speed is nothing without correctness. Practice writing dry-run assertions on paper before typing a single line of code.",
      raven: "Meta won't forgive hesitation. Solve in O(N) space and time, write clean code, and test your own edge cases.",
      atlas: "Meta compensation tops global benchmarks. Positioning yourself as a high-velocity product engineer opens the door.",
      sage: "We will drill timed LeetCode sets under strict 20-minute constraints to build your muscle memory for Meta's bar.",
    },
  },
  {
    id: "amazon",
    name: "Amazon",
    logo: "amazon",
    industry: "E-commerce, Cloud & Logistics",
    category: "Big Tech / FAANG+",
    workMode: "Hybrid",
    scale: "1.5M+ Employees",
    headquarters: "Seattle, WA",
    salaryRange: "₹22L–58L",
    estimatedPrepMonths: 6,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Java",
      "AWS",
      "Python",
      "C++",
      "DynamoDB",
      "Docker",
      "Kubernetes",
      "React",
      "TypeScript",
    ],
    typicalRoles: [
      "Backend Developer",
      "Software Engineer",
      "Cloud Engineer",
      "DevOps Engineer",
      "Data Scientist",
    ],
    aliases: [
      "AWS",
      "Amazon Web Services",
      "Prime Video",
      "Alexa",
      "Kindle",
      "Audible",
      "Twitch",
      "S3",
      "EC2",
      "DynamoDB",
      "Amazon.com",
    ],
    misspellings: ["Amzon", "Amazn", "Amzn"],
    interviewStages: [
      { name: "Online Assessment (OA1 & OA2)", desc: "Debugging, DSA and Work Style Simulation", type: "oa" },
      { name: "Technical Coding Round", desc: "Object-oriented design and algorithmic solutions", type: "technical" },
      { name: "System Design", desc: "Scalable microservices, asynchronous queues, caching", type: "system_design" },
      { name: "Bar Raiser Interview", desc: "Rigorous evaluation against Amazon's 16 Leadership Principles", type: "managerial" },
    ],
    topSkillsNeeded: ["Java / OOP", "AWS Microservices", "System Design", "Leadership Principles (Customer Obsession, Ownership)"],
    relatedCompanyIds: ["microsoft", "google", "uber", "netflix", "flipkart"],
    mentorCommentary: {
      nova: "At Amazon, your leadership stories matter just as much as your code. Every technical question connects back to Leadership Principles.",
      athena: "Learn to articulate the 'Customer Obsession' trade-offs in your design decisions. Amazon values long-term architecture over quick patches.",
      byte: "Practice object-oriented design patterns—Parking Lot, File System, Elevator. Amazon loves low-level class design.",
      raven: "At Amazon, the Bar Raiser has veto power. Fail their behavioral probe or stutter on your data partition key, and you're out.",
      atlas: "Amazon is one of the highest volume recruiters of ambitious software engineers. An optimized resume gets screened within 48 hours.",
      sage: "We'll build a personalized STAR interview matrix covering all 16 Leadership Principles so you never freeze under behavioral scrutiny.",
    },
  },
  {
    id: "apple",
    name: "Apple",
    logo: "apple",
    industry: "Consumer Tech, Hardware & Services",
    category: "Big Tech / FAANG+",
    workMode: "On-site",
    scale: "160k+ Employees",
    headquarters: "Cupertino, CA",
    salaryRange: "₹24L–65L",
    estimatedPrepMonths: 7,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Swift",
      "SwiftUI",
      "Objective-C",
      "C++",
      "C",
      "Python",
      "Metal",
      "CoreData",
    ],
    typicalRoles: [
      "iOS Engineer",
      "Software Engineer",
      "Machine Learning Engineer",
      "UI/UX Designer",
    ],
    aliases: [
      "Swift",
      "SwiftUI",
      "Xcode",
      "Vision Pro",
      "iOS",
      "macOS",
      "iPadOS",
      "watchOS",
      "Metal",
      "Apple Ecosystem",
      "Apple Silicon",
    ],
    misspellings: ["Appel", "Aple"],
    interviewStages: [
      { name: "Recruiter Screen", desc: "Background overview and iOS/Apple ecosystem depth", type: "hr" },
      { name: "Technical Screen", desc: "Swift, memory management (ARC), and DSA problem solving", type: "technical" },
      { name: "Onsite Technical (x4)", desc: "System architecture, concurrency, buttery 120Hz UI rendering", type: "technical" },
      { name: "Team Fit & Craftsmanship", desc: "Attention to detail, perfectionism, and design empathy", type: "managerial" },
    ],
    topSkillsNeeded: ["Swift & SwiftUI", "Memory Management (ARC)", "Buttery 120Hz Animation Performance", "C++ / Objective-C"],
    relatedCompanyIds: ["google", "meta", "microsoft", "spotify", "uber"],
    mentorCommentary: {
      nova: "Apple cares about extreme craftsmanship. Even your variable names and micro-interactions should reflect obsessive care.",
      athena: "Expect deep questions on computer architecture, memory allocation, and operating system kernels alongside clean Swift code.",
      byte: "Master Automatic Reference Counting (ARC), retain cycles, and GCD/async concurrency. Apple digs deep into runtimes.",
      raven: "Apple will not tolerate sloppy code or laggy frame rates. You either respect the hardware or you don't work in Cupertino.",
      atlas: "Having a deployed App Store product with positive user reviews gives you immense credibility with Apple engineering managers.",
      sage: "We will dedicate targeted milestones to Swift concurrency, SwiftUI component lifecycles, and Apple HIG design benchmarks.",
    },
  },
  {
    id: "netflix",
    name: "Netflix",
    logo: "netflix",
    industry: "Streaming Entertainment & Distributed Tech",
    category: "Big Tech / FAANG+",
    workMode: "Remote-friendly",
    scale: "13k+ Employees",
    headquarters: "Los Gatos, CA",
    salaryRange: "₹35L–85L",
    estimatedPrepMonths: 8,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Java",
      "Spring Boot",
      "Node.js",
      "AWS",
      "Kafka",
      "Cassandra",
      "React",
      "GraphQL",
    ],
    typicalRoles: [
      "Backend Developer",
      "Software Engineer",
      "DevOps Engineer",
      "Cloud Engineer",
      "Data Scientist",
    ],
    aliases: [
      "Netflix Tech",
      "Chaos Engineering",
      "Spinnaker",
      "Zuul",
      "Eureka",
      "Hystrix",
      "Conductor",
      "Netflix OSS",
    ],
    misspellings: ["Netflx", "Netlfix", "Netfix"],
    interviewStages: [
      { name: "Technical Screen", desc: "Live distributed systems coding and data structure trade-offs", type: "technical" },
      { name: "Onsite Round 1 & 2", desc: "High-throughput microservices, resiliency, chaos engineering", type: "system_design" },
      { name: "Culture & Philosophy", desc: "Freedom & Responsibility memo deep-dive with Engineering Directors", type: "managerial" },
    ],
    topSkillsNeeded: ["Distributed Systems Resiliency", "High-Throughput Messaging (Kafka)", "Java / Spring Boot", "Culture of Candor"],
    relatedCompanyIds: ["amazon", "meta", "uber", "stripe", "google"],
    mentorCommentary: {
      nova: "Netflix only hires high-judgment engineers who thrive with freedom and responsibility. Show extreme ownership in past decisions.",
      athena: "Read the Netflix Culture Deck three times. They evaluate your candid feedback approach as much as your Kafka throughput.",
      byte: "Know how Netflix handles massive traffic spikes. Study circuit breakers, adaptive rate limiting, and multi-region failovers.",
      raven: "Netflix pays top of market in all cash, but they cut low performers without hesitation. Bring top-of-game architecture.",
      atlas: "Senior engineers at Netflix command industry-leading salaries. Highlighting independent production impact is your ticket.",
      sage: "Our curriculum will prepare you to architect distributed event pipelines and defend fault-tolerant cloud systems under failure.",
    },
  },

  // =========================================================================
  // 2. AI LEADERS & RESEARCH
  // =========================================================================
  {
    id: "openai",
    name: "OpenAI",
    logo: "openai",
    industry: "Artificial Intelligence & AGI Research",
    category: "AI Leaders & Research",
    workMode: "Hybrid",
    scale: "1,500+ Employees",
    headquarters: "San Francisco, CA",
    salaryRange: "₹35L–90L",
    estimatedPrepMonths: 9,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Python",
      "PyTorch",
      "CUDA",
      "Triton",
      "Kubernetes",
      "Rust",
      "Distributed Training",
      "Vector DBs",
    ],
    typicalRoles: [
      "AI Engineer",
      "Machine Learning Engineer",
      "Software Engineer",
      "Backend Developer",
    ],
    aliases: [
      "ChatGPT",
      "GPT",
      "GPT-4",
      "GPT-4o",
      "DALL-E",
      "Sora",
      "Whisper",
      "OpenAI Research",
      "Embeddings",
      "OpenAI API",
    ],
    misspellings: ["Open AI", "Openai", "Open-ai"],
    interviewStages: [
      { name: "Take-Home Engineering Challenge", desc: "Realistic ML infrastructure or systems challenge", type: "oa" },
      { name: "Code Review & Technical Screen", desc: "Walking through challenge optimizations with OpenAI researcher", type: "technical" },
      { name: "Onsite Technical Rounds (x3)", desc: "Distributed training, GPU kernels, PyTorch internals & algorithmic depth", type: "technical" },
      { name: "Research & Mission Alignment", desc: "Safeguarding AGI and technical communication", type: "managerial" },
    ],
    topSkillsNeeded: ["PyTorch / Deep Learning Internals", "Distributed Model Training", "GPU Memory Optimization (CUDA/Triton)", "Python / Rust"],
    relatedCompanyIds: ["anthropic", "nvidia", "google", "meta", "databricks"],
    mentorCommentary: {
      nova: "OpenAI moves at breakneck speed. Showing working projects built with LLMs, RAG, and eval benchmarks sets you apart.",
      athena: "Demonstrate deep conceptual mastery of transformer attention mechanisms and mathematical optimization.",
      byte: "You must know how memory transfers work across GPU clusters. Brush up on FlashAttention, KV caching, and quantization.",
      raven: "OpenAI is the frontier of computing. Don't show up with a toy tutorial project. Build something with measurable evaluation.",
      atlas: "OpenAI offers unparalleled equity upside and brand prestige. An AI-targeted portfolio is mandatory.",
      sage: "We'll build out a rigorous 9-month pathway combining advanced PyTorch modeling with high-scale LLM application architectures.",
    },
  },
  {
    id: "anthropic",
    name: "Anthropic",
    logo: "anthropic",
    industry: "AI Safety & Foundation Models",
    category: "AI Leaders & Research",
    workMode: "Hybrid",
    scale: "800+ Employees",
    headquarters: "San Francisco, CA",
    salaryRange: "₹35L–85L",
    estimatedPrepMonths: 9,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Python",
      "PyTorch",
      "Rust",
      "JAX",
      "Distributed Systems",
      "Kubernetes",
      "AWS",
    ],
    typicalRoles: [
      "AI Engineer",
      "Machine Learning Engineer",
      "Software Engineer",
      "Backend Developer",
    ],
    aliases: [
      "Claude",
      "Claude 3",
      "Claude 3.5 Sonnet",
      "Constitutional AI",
      "Anthropic AI",
    ],
    misspellings: ["Antropic", "Anthropik"],
    interviewStages: [
      { name: "Practical Systems Assessment", desc: "Distributed ML systems or Python algorithm challenge", type: "oa" },
      { name: "Technical Discussion", desc: "Deep dive into challenge code and architectural trade-offs", type: "technical" },
      { name: "Onsite Coding & Architecture", desc: "Model evaluation, high-throughput pipelines, and AI safety benchmarks", type: "technical" },
      { name: "Culture & Safety Alignment", desc: "Constitutional AI and responsible model deployment", type: "managerial" },
    ],
    topSkillsNeeded: ["Transformer Architectures", "Python & PyTorch", "Distributed Systems Scaling", "Responsible AI Governance"],
    relatedCompanyIds: ["openai", "google", "meta", "nvidia", "databricks"],
    mentorCommentary: {
      nova: "Anthropic values both extreme capability and safety. Highlighting evaluation pipelines and agentic tooling is your edge.",
      athena: "Constitutional AI and interpretability are core to Anthropic. Read their research papers on mechanistic interpretability.",
      byte: "Be ready to debug memory leaks in training loops and explain asynchronous data loaders in distributed PyTorch.",
      raven: "Anthropic researchers will dismantle weak claims. Ground every architectural assertion in hard benchmark numbers.",
      atlas: "Anthropic is competing directly with Big Tech and OpenAI. A high-impact background in Python and distributed systems gets fast-tracked.",
      sage: "We will chart a specialized roadmap focusing on model evals, RAG vector pipelines, and production inference performance.",
    },
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    logo: "nvidia",
    industry: "Accelerated Computing, GPUs & AI Hardware",
    category: "Semiconductor & Hardware",
    workMode: "Hybrid",
    scale: "30k+ Employees",
    headquarters: "Santa Clara, CA",
    salaryRange: "₹25L–65L",
    estimatedPrepMonths: 8,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "CUDA",
      "C++",
      "Python",
      "PyTorch",
      "TensorRT",
      "C",
      "Linux",
      "Computer Architecture",
    ],
    typicalRoles: [
      "Machine Learning Engineer",
      "AI Engineer",
      "Software Engineer",
      "Game Developer",
    ],
    aliases: [
      "CUDA",
      "GeForce",
      "RTX",
      "Omniverse",
      "TensorRT",
      "DGX",
      "NVDA",
      "Nvidia AI",
      "Jetson",
    ],
    misspellings: ["Nvidiaa", "Nvida", "Nvidea"],
    interviewStages: [
      { name: "Technical Screen", desc: "C++, memory hierarchies, pointers and bitwise manipulation", type: "technical" },
      { name: "Coding Assessment", desc: "Algorithmic optimization and thread-level parallelism", type: "oa" },
      { name: "Onsite Technical Rounds (x4)", desc: "CUDA kernel design, memory coalescing, GPU hardware architecture", type: "technical" },
      { name: "Engineering Director Fit", desc: "Problem ownership and high-speed execution", type: "managerial" },
    ],
    topSkillsNeeded: ["CUDA Programming", "Modern C++ (17/20)", "Computer Architecture & Cache Hierarchy", "TensorRT Optimization"],
    relatedCompanyIds: ["openai", "google", "meta", "apple", "microsoft"],
    mentorCommentary: {
      nova: "NVIDIA powers the entire global AI boom. If you love low-level performance, GPU parallelism, and raw speed, this is the peak.",
      athena: "Understand cache misses, thread warps, and SIMD/SIMT architectures. NVIDIA tests your foundational hardware understanding.",
      byte: "Master pointers, volatile variables, mutexes, and CUDA memory models. High-level abstractions won't fly here.",
      raven: "NVIDIA does not tolerate memory leaks or uncoalesced memory reads. Your C++ code must be surgically optimized.",
      atlas: "NVIDIA has achieved historic market capitalization. Securing an engineering role here represents a life-changing career milestone.",
      sage: "We will allocate focused study modules to C++ concurrency, GPU memory structures, and inference acceleration with TensorRT.",
    },
  },

  // =========================================================================
  // 3. GLOBAL PRODUCT UNICORNS & HIGH-SCALE SAAS
  // =========================================================================
  {
    id: "uber",
    name: "Uber",
    logo: "uber",
    industry: "Mobility, Logistics & High-Throughput Tech",
    category: "Global Product Unicorns",
    workMode: "Hybrid",
    scale: "32k+ Employees",
    headquarters: "San Francisco, CA",
    salaryRange: "₹24L–60L",
    estimatedPrepMonths: 6,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Go",
      "Java",
      "Python",
      "Kafka",
      "Cassandra",
      "Microservices",
      "React",
      "Kotlin",
      "Swift",
    ],
    typicalRoles: [
      "Backend Developer",
      "Software Engineer",
      "Android Engineer",
      "iOS Engineer",
      "Full Stack Engineer",
    ],
    aliases: ["Uber Technologies", "Uber Eats", "Uber Freight", "Cadence", "Jaeger"],
    misspellings: ["Ubr", "Ubar"],
    interviewStages: [
      { name: "Online Coding Screen", desc: "HackerRank assessment with 3 DSA questions", type: "oa" },
      { name: "Technical Phone Screen", desc: "Real-time algorithmic coding and complexity analysis", type: "technical" },
      { name: "System Design Onsite", desc: "Designing high-concurrency geospatial mapping & dispatch systems", type: "system_design" },
      { name: "Hiring Manager Round", desc: "Past engineering impact and cultural alignment", type: "managerial" },
    ],
    topSkillsNeeded: ["Go / Java Backend", "Geospatial & High-Concurrency Systems", "Kafka Event Streaming", "System Design"],
    relatedCompanyIds: ["stripe", "netflix", "amazon", "swiggy", "zomato"],
    mentorCommentary: {
      nova: "Uber handles millions of simultaneous rides and geospatial lookups. Microservices and low latency in Go/Java are huge advantages.",
      athena: "Study distributed consensus, geohashing (H3 algorithm), and transaction locking under high contention.",
      byte: "Know how real-time dispatch works. Practice designing Uber's backend architecture with web sockets and Kafka queues.",
      raven: "Uber's system design is legendary. If you don't know how to handle race conditions in seat bookings, you will fail.",
      atlas: "Uber India R&D centers in Bengaluru and Hyderabad build core global systems. It's a gold-standard engineering brand.",
      sage: "We'll build dedicated modules on high-throughput distributed architectures, geospatial indexing, and real-time event streaming.",
    },
  },
  {
    id: "stripe",
    name: "Stripe",
    logo: "stripe",
    industry: "Financial Infrastructure & Payments API",
    category: "FinTech & Payments",
    workMode: "Remote-friendly",
    scale: "8k+ Employees",
    headquarters: "South San Francisco, CA",
    salaryRange: "₹28L–70L",
    estimatedPrepMonths: 7,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "Ruby",
      "Go",
      "Java",
      "TypeScript",
      "React",
      "Sorbet",
      "PostgreSQL",
      "Kafka",
    ],
    typicalRoles: [
      "Backend Developer",
      "Full Stack Engineer",
      "Software Engineer",
      "Frontend Developer",
    ],
    aliases: ["Stripe Payments", "Stripe API", "Stripe Connect", "Radar", "Stripe Billing"],
    misspellings: ["Stripey", "Stripp"],
    interviewStages: [
      { name: "Practical Coding Screen", desc: "Debugging and implementing real-world API features in your own IDE", type: "technical" },
      { name: "Bug Squash & Integration", desc: "Finding and fixing bugs in an open-source codebase live", type: "technical" },
      { name: "API & System Architecture", desc: "Designing idempotent, fault-tolerant financial billing schemas", type: "system_design" },
      { name: "Culture & Communication", desc: "Clear written technical communication and craftsmanship", type: "hr" },
    ],
    topSkillsNeeded: ["API Design & Idempotency", "Database ACID Transactions", "Practical Debugging in Local IDE", "Clean Code"],
    relatedCompanyIds: ["uber", "razorpay", "atlassian", "meta", "netflix"],
    mentorCommentary: {
      nova: "Stripe doesn't do puzzle LeetCode. They test real-world developer skills—building APIs and debugging code in your own IDE.",
      athena: "Stripe treats API design as high art. Read their API documentation to understand idempotency keys and error handling.",
      byte: "Idempotency, webhooks, and retry mechanisms. If you can't guarantee money isn't charged twice, Stripe won't hire you.",
      raven: "Stripe is obsessed with written clarity and craftsmanship. If your variable naming is sloppy, they won't even invite you to onsite.",
      atlas: "Stripe is widely recognized as one of the best engineering cultures in tech. Remote-first with Silicon Valley compensation.",
      sage: "We will structure hands-on projects building production-ready Stripe-style webhooks, idempotency keys, and transaction ledgers.",
    },
  },
  {
    id: "atlassian",
    name: "Atlassian",
    logo: "atlassian",
    industry: "Team Collaboration & Enterprise Software",
    category: "Global Product Unicorns",
    workMode: "Remote-friendly",
    scale: "11k+ Employees",
    headquarters: "Sydney, Australia",
    salaryRange: "₹22L–55L",
    estimatedPrepMonths: 6,
    hiringDifficulty: 4,
    primaryTechnologies: [
      "Java",
      "Spring Boot",
      "React",
      "TypeScript",
      "AWS",
      "GraphQL",
      "Microservices",
    ],
    typicalRoles: [
      "Backend Developer",
      "Full Stack Engineer",
      "Frontend Developer",
      "DevOps Engineer",
    ],
    aliases: ["Jira", "Confluence", "Bitbucket", "Trello", "Atlassian Cloud"],
    misspellings: ["Atlasian", "Attlassian"],
    interviewStages: [
      { name: "Online Assessment", desc: "HackerRank DSA and coding questions", type: "oa" },
      { name: "Coding & Design Screen", desc: "Clean object-oriented code with unit tests", type: "technical" },
      { name: "System Architecture Onsite", desc: "Designing multi-tenant SaaS platforms on AWS", type: "system_design" },
      { name: "Values & Behavioral Round", desc: "Living the 5 Atlassian core values (Open Company, No Bullshit)", type: "hr" },
    ],
    topSkillsNeeded: ["Java / Spring Boot", "React & Modern UI", "Multi-Tenant SaaS Architecture", "Core Values Fit"],
    relatedCompanyIds: ["microsoft", "google", "zoho", "freshworks", "postman"],
    mentorCommentary: {
      nova: "Atlassian's 'TEAM Anywhere' policy lets you work from anywhere. Their engineering standard in Java and React is world-class.",
      athena: "Study their core value: 'Open company, no bullshit'. They respect transparent candidates who admit what they don't know.",
      byte: "Write unit tests during your live coding round. Atlassian loves test-driven development and clean modular abstractions.",
      raven: "Atlassian will instantly reject arrogant candidates. Be humble, write solid code, and justify every architectural choice.",
      atlas: "Atlassian offers some of the highest entry-level packages in India with exceptional work-life balance.",
      sage: "We will focus on full-stack Java/React integration, clean TDD practices, and multi-tenant cloud design benchmarks.",
    },
  },

  // =========================================================================
  // 4. INDIAN PRODUCT UNICORNS & FAST-GROWING STARTUPS
  // =========================================================================
  {
    id: "zoho",
    name: "Zoho",
    logo: "zoho",
    industry: "Business Software & Cloud Applications",
    category: "Indian Product Unicorns",
    workMode: "On-site",
    scale: "15k+ Employees",
    headquarters: "Chennai, India",
    salaryRange: "₹8L–25L",
    estimatedPrepMonths: 4,
    hiringDifficulty: 3,
    primaryTechnologies: [
      "Java",
      "C++",
      "JavaScript",
      "PostgreSQL",
      "MySQL",
      "Linux",
      "Self-Hosted Cloud",
    ],
    typicalRoles: [
      "Software Engineer",
      "Backend Developer",
      "Full Stack Engineer",
      "UI/UX Designer",
    ],
    aliases: ["Zoho Corp", "Zoho CRM", "Zoho Books", "ManageEngine", "Zoho One"],
    misspellings: ["Zho", "Zohocorp"],
    interviewStages: [
      { name: "Basic Aptitude & C/Java", desc: "Mathematical aptitude and C/Java programming basics", type: "oa" },
      { name: "Advanced Programming Round", desc: "Complex logic implementation without built-in library shortcuts", type: "technical" },
      { name: "Design & Logic Round", desc: "Object-oriented design (e.g. Railway Reservation, Snake Game)", type: "technical" },
      { name: "HR & Cultural Fit", desc: "Problem solving attitude and long-term commitment", type: "hr" },
    ],
    topSkillsNeeded: ["Raw Problem Solving in C/Java", "String Manipulation & Data Structures", "Object-Oriented Design", "Deep Logic"],
    relatedCompanyIds: ["freshworks", "chargebee", "postman", "atlassian"],
    mentorCommentary: {
      nova: "Zoho values pure problem-solving and algorithmic logic without depending on high-level library shortcuts. A legendary product pioneer!",
      athena: "Zoho asks you to build games and reservation systems from scratch in C or Java. Focus on raw procedural and object logic.",
      byte: "No external libraries allowed in Zoho rounds. Master memory management, basic arrays, recursion, and clean loops.",
      raven: "Zoho tests your real coding stamina across 4+ hours of raw programming. No fancy buzzwords—just working code.",
      atlas: "Zoho has built a multibillion-dollar bootstrapped empire from Chennai. It is one of India's most respected product engineering nurseries.",
      sage: "We will drill deep into raw logic puzzles, string processing, and full application simulations in C and Java.",
    },
  },
  {
    id: "freshworks",
    name: "Freshworks",
    logo: "freshworks",
    industry: "Customer Engagement & SaaS Software",
    category: "Indian Product Unicorns",
    workMode: "Hybrid",
    scale: "5k+ Employees",
    headquarters: "San Mateo, CA & Chennai, India",
    salaryRange: "₹14L–36L",
    estimatedPrepMonths: 5,
    hiringDifficulty: 4,
    primaryTechnologies: [
      "Ruby on Rails",
      "Java",
      "Node.js",
      "React",
      "AWS",
      "Kafka",
      "MySQL",
    ],
    typicalRoles: [
      "Backend Developer",
      "Full Stack Engineer",
      "Frontend Developer",
      "DevOps Engineer",
    ],
    aliases: ["Freshdesk", "Freshservice", "Freshsales", "Freshchat", "FRSH"],
    misspellings: ["Freshwork", "Fresh-works"],
    interviewStages: [
      { name: "Online Coding Screen", desc: "HackerRank problem solving and data structures", type: "oa" },
      { name: "Technical Round 1", desc: "DSA, time complexity, and clean code implementation", type: "technical" },
      { name: "System Design Round", desc: "Designing multi-tenant SaaS helpdesk and messaging queues", type: "system_design" },
      { name: "Managerial & Culture", desc: "Team collaboration, customer empathy, and problem ownership", type: "managerial" },
    ],
    topSkillsNeeded: ["Java / Ruby on Rails", "RESTful APIs", "React UI Framework", "Distributed Caching"],
    relatedCompanyIds: ["zoho", "chargebee", "postman", "razorpay"],
    mentorCommentary: {
      nova: "Freshworks proved Indian SaaS can trade on Nasdaq. They look for clean, responsive full-stack engineers who ship fast.",
      athena: "Prepare for scalable multi-tenant database designs and asynchronous background jobs with Redis and Kafka.",
      byte: "Keep your code modular and readable. Freshworks evaluates code readability and maintainability very highly.",
      raven: "Freshworks moves fast. Show them you can design an API that doesn't collapse when 10,000 agents submit tickets simultaneously.",
      atlas: "Freshworks offers great equity grants and a vibrant global SaaS culture between Chennai and the US.",
      sage: "We will build a portfolio showcasing end-to-end SaaS ticketing and CRM workflows with scalable REST endpoints.",
    },
  },
  {
    id: "postman",
    name: "Postman",
    logo: "postman",
    industry: "API Platform & Developer Productivity",
    category: "Indian Product Unicorns",
    workMode: "Remote-friendly",
    scale: "1,200+ Employees",
    headquarters: "San Francisco, CA & Bengaluru, India",
    salaryRange: "₹20L–50L",
    estimatedPrepMonths: 6,
    hiringDifficulty: 4,
    primaryTechnologies: [
      "Node.js",
      "TypeScript",
      "React",
      "Electron",
      "Go",
      "AWS",
      "Docker",
      "GraphQL",
    ],
    typicalRoles: [
      "Full Stack Engineer",
      "Backend Developer",
      "Frontend Developer",
      "DevOps Engineer",
    ],
    aliases: ["Postman API", "Newman", "Postman Enterprise", "Postman App"],
    misspellings: ["Postmn", "Post man"],
    interviewStages: [
      { name: "Practical API Challenge", desc: "Building or consuming realistic APIs with clean error handling", type: "oa" },
      { name: "Technical Deep Dive", desc: "Node.js event loop, Electron architecture, and React rendering", type: "technical" },
      { name: "System Architecture", desc: "Scaling API request parsing and real-time collaboration servers", type: "system_design" },
      { name: "Culture & Values", desc: "Developer empathy, high curiosity, and user-centric engineering", type: "hr" },
    ],
    topSkillsNeeded: ["Deep API Protocols (REST, GraphQL, gRPC, WebSockets)", "Node.js & TypeScript", "Electron Desktop Engineering", "Developer Empathy"],
    relatedCompanyIds: ["atlassian", "razorpay", "freshworks", "github"],
    mentorCommentary: {
      nova: "Over 30 million developers use Postman every single day! Building tools for developers is the ultimate engineering thrill.",
      athena: "Master HTTP specification, headers, status codes, WebSocket handshakes, and gRPC. Postman expects deep protocol fluency.",
      byte: "Understand the Node.js event loop and V8 internals. Postman tests your JavaScript/TypeScript mastery down to the byte.",
      raven: "If you build developer tools, your errors must be crystal clear and your performance must be instantaneous.",
      atlas: "Postman is one of the highest valued developer tool unicorns in the world. Exceptional remote culture and top compensation.",
      sage: "We will tailor your learning to modern API specifications, OpenAPI schemas, and high-performance TypeScript architectures.",
    },
  },
  {
    id: "razorpay",
    name: "Razorpay",
    logo: "razorpay",
    industry: "FinTech, Payments & Banking Infrastructure",
    category: "FinTech & Payments",
    workMode: "Hybrid",
    scale: "3,500+ Employees",
    headquarters: "Bengaluru, India",
    salaryRange: "₹18L–45L",
    estimatedPrepMonths: 6,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "PHP",
      "Go",
      "Node.js",
      "Python",
      "React",
      "Kafka",
      "AWS",
      "Kubernetes",
      "MySQL",
    ],
    typicalRoles: [
      "Backend Developer",
      "Full Stack Engineer",
      "Frontend Developer",
      "DevOps Engineer",
    ],
    aliases: ["Razorpay Payments", "RazorpayX", "Opfin", "Curlec"],
    misspellings: ["Razor pay", "Razorpai", "Razorpy"],
    interviewStages: [
      { name: "Coding Round", desc: "DSA and problem solving on HackerEarth/HackerRank", type: "oa" },
      { name: "Machine Coding Round", desc: "Live 90-min implementation of a working software subsystem", type: "technical" },
      { name: "High-Level System Design", desc: "Payment gateway routing, ledger consistency, idempotency", type: "system_design" },
      { name: "Hiring Manager & Culture", desc: "Customer focus, hustle, and architectural resilience", type: "managerial" },
    ],
    topSkillsNeeded: ["Machine Coding Speed", "Distributed Financial Ledgers", "Go / Java / PHP", "System Design"],
    relatedCompanyIds: ["stripe", "phonepe", "cred", "swiggy", "zomato"],
    mentorCommentary: {
      nova: "Razorpay powers billions of transactions across India. Their famous Machine Coding round tests how cleanly you can build in 90 minutes.",
      athena: "Focus on clean OOP design patterns: Factory, Strategy, and Observer. Write modular code with clear separation of concerns.",
      byte: "ACID compliance and distributed locking. When handling payments, you cannot drop a single byte or duplicate a rupee.",
      raven: "Razorpay's Machine Coding round weeds out slow typers and copy-paste coders. Practice building fully working CLI apps in under 90 minutes.",
      atlas: "Razorpay is India's leading fintech unicorn and a premier brand on any resume. Top tier compensation and high engineering standards.",
      sage: "We will practice timed 90-minute machine coding simulations for parking lots, splitwise, and payment routing engines.",
    },
  },

  // =========================================================================
  // 5. GAMING & INTERACTIVE
  // =========================================================================
  {
    id: "epic-games",
    name: "Epic Games",
    logo: "epic-games",
    industry: "Gaming, Game Engines & Virtual Worlds",
    category: "Gaming & Interactive",
    workMode: "Hybrid",
    scale: "4,000+ Employees",
    headquarters: "Cary, NC",
    salaryRange: "₹25L–60L",
    estimatedPrepMonths: 8,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "C++",
      "Unreal Engine",
      "Unreal Engine 5",
      "Blueprints",
      "HLSL",
      "Shaders",
      "Python",
      "DirectX",
    ],
    typicalRoles: [
      "Game Developer",
      "Software Engineer",
      "UI/UX Designer",
    ],
    aliases: [
      "Unreal Engine",
      "UE5",
      "UE4",
      "Fortnite",
      "Epic Games Store",
      "MetaHuman",
      "Epic Online Services",
    ],
    misspellings: ["Epicgames", "Epick Games"],
    interviewStages: [
      { name: "Take-Home C++ Gameplay Challenge", desc: "Implementing a custom 3D gameplay mechanic in Unreal Engine", type: "oa" },
      { name: "Technical C++ Deep Dive", desc: "Pointers, memory layout, game loops, physics simulations", type: "technical" },
      { name: "Graphics & Engine Architecture", desc: "Shaders, rendering pipeline, Nanite/Lumen performance", type: "system_design" },
      { name: "Cultural & Creative Fit", desc: "Passion for game design, player experience, and engineering rigor", type: "hr" },
    ],
    topSkillsNeeded: ["Modern C++ (17/20)", "Unreal Engine 5 Internals", "3D Math & Matrix Transformations", "Shader Programming (HLSL)"],
    relatedCompanyIds: ["riot-games", "rockstar-games", "valve", "unity", "nvidia"],
    mentorCommentary: {
      nova: "Epic Games powers both Fortnite and the world's greatest virtual productions with Unreal Engine 5. Game dev heaven!",
      athena: "You need rock-solid linear algebra, quaternion rotations, and physics simulation math alongside modern C++.",
      byte: "Frame rates cannot drop below 60fps. Master memory cache locality, spatial partitioning, and multi-threaded rendering.",
      raven: "Game engineering is the hardest discipline in software. If you don't know matrix math, don't waste Epic's time.",
      atlas: "Unreal Engine skills are in massive demand across gaming, Hollywood virtual production, and robotics simulation.",
      sage: "We will build a portfolio game in Unreal Engine 5 demonstrating C++ gameplay mechanics, shaders, and multiplayer networking.",
    },
  },
  {
    id: "riot-games",
    name: "Riot Games",
    logo: "riot-games",
    industry: "Competitive Gaming & Esports",
    category: "Gaming & Interactive",
    workMode: "Hybrid",
    scale: "4,500+ Employees",
    headquarters: "Los Angeles, CA",
    salaryRange: "₹24L–60L",
    estimatedPrepMonths: 7,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "C++",
      "Java",
      "Go",
      "Python",
      "Unreal Engine",
      "AWS",
      "Docker",
      "React",
    ],
    typicalRoles: [
      "Game Developer",
      "Backend Developer",
      "Software Engineer",
      "Full Stack Engineer",
    ],
    aliases: ["League of Legends", "Valorant", "TFT", "Teamfight Tactics", "Wild Rift", "Riot Forge"],
    misspellings: ["Riotgames", "Roit Games"],
    interviewStages: [
      { name: "Online Coding Screen", desc: "HackerRank algorithms and gameplay math", type: "oa" },
      { name: "Technical Screening", desc: "C++ / Java object-oriented design and network latency handling", type: "technical" },
      { name: "System Architecture & Game Loops", desc: "Designing tick-rate synchronization, client prediction, lag compensation", type: "system_design" },
      { name: "Gamer Empathy & Culture", desc: "Player-first philosophy and anti-toxicity mechanics", type: "hr" },
    ],
    topSkillsNeeded: ["C++ / Go Backend", "Client-Server Network Sync", "Low Latency Networking (UDP)", "Player Empathy"],
    relatedCompanyIds: ["epic-games", "rockstar-games", "valve", "sony", "unity"],
    mentorCommentary: {
      nova: "Riot built League of Legends and Valorant. They obsess over 128-tick game servers and zero-lag competitive integrity.",
      athena: "Study deterministic lockstep, client-side prediction, and server reconciliation. Networked gaming requires rigorous math.",
      byte: "Every millisecond counts when handling hit registration in Valorant. Master UDP sockets, binary serialization, and packet compression.",
      raven: "Riot will test your passion as a player and your ruthlessness as an engineer. Deliver clean code or get eliminated.",
      atlas: "Riot Games offers one of the most beloved engineering and creative cultures in global entertainment.",
      sage: "We will build projects featuring real-time multiplayer sockets, authoritative game servers, and predictive movement.",
    },
  },

  // =========================================================================
  // 6. CYBER SECURITY LEADERS
  // =========================================================================
  {
    id: "palo-alto-networks",
    name: "Palo Alto Networks",
    logo: "palo-alto-networks",
    industry: "Enterprise Cybersecurity & Cloud Defense",
    category: "Cyber Security",
    workMode: "Hybrid",
    scale: "15k+ Employees",
    headquarters: "Santa Clara, CA",
    salaryRange: "₹20L–50L",
    estimatedPrepMonths: 7,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "C",
      "C++",
      "Python",
      "Go",
      "Linux Kernel",
      "Networking",
      "Cloud Security",
      "SIEM",
    ],
    typicalRoles: [
      "Cyber Security Analyst",
      "Software Engineer",
      "Cloud Engineer",
      "DevOps Engineer",
    ],
    aliases: ["PANW", "Prisma Cloud", "Cortex", "Cortex XDR", "Strata"],
    misspellings: ["Paloalto", "Palo Alto Network"],
    interviewStages: [
      { name: "Online Technical Assessment", desc: "Network protocols, OS fundamentals, and coding algorithms", type: "oa" },
      { name: "Technical Rounds (x3)", desc: "Packet inspection, socket programming, cryptography, and vulnerability detection", type: "technical" },
      { name: "Security Architecture", desc: "Zero Trust architecture, firewall scaling, and malware analysis", type: "system_design" },
      { name: "Managerial Fit", desc: "Incident response under pressure and team ownership", type: "managerial" },
    ],
    topSkillsNeeded: ["TCP/IP & OSI Stack", "C / C++ Kernel Programming", "Network Security & Cryptography", "Linux Internals"],
    relatedCompanyIds: ["crowdstrike", "cloudflare", "cisco", "microsoft", "google"],
    mentorCommentary: {
      nova: "Palo Alto Networks is the undisputed global giant of cybersecurity. Protecting thousands of global enterprises every second!",
      athena: "Understand the TCP/IP handshake, TLS encryption handshakes, and packet routing deeply. Security starts at the transport layer.",
      byte: "Brush up on buffer overflows, stack memory layout, and socket programming in C/C++. PANW tests true computer science depth.",
      raven: "In cyber defense, one flaw means a billion-dollar breach. Your code must have zero buffer vulnerabilities.",
      atlas: "Cybersecurity engineers enjoy virtually unshakeable job security and top compensation tiers globally.",
      sage: "We will prepare hands-on modules in network packet capture (Wireshark), socket programming, and Zero Trust security models.",
    },
  },
  {
    id: "crowdstrike",
    name: "CrowdStrike",
    logo: "crowdstrike",
    industry: "Cloud-Native Endpoint Security & Threat Intelligence",
    category: "Cyber Security",
    workMode: "Remote-friendly",
    scale: "8k+ Employees",
    headquarters: "Austin, TX",
    salaryRange: "₹22L–55L",
    estimatedPrepMonths: 7,
    hiringDifficulty: 5,
    primaryTechnologies: [
      "C++",
      "Go",
      "Python",
      "Kernel Drivers",
      "Kafka",
      "Cassandra",
      "AWS",
    ],
    typicalRoles: [
      "Cyber Security Analyst",
      "Software Engineer",
      "Backend Developer",
      "Cloud Engineer",
    ],
    aliases: ["Falcon", "Crowdstrike Falcon", "CRWD", "Falcon Sensor"],
    misspellings: ["Crowd strike", "CrowdStryke"],
    interviewStages: [
      { name: "Technical Coding Screen", desc: "Algorithmic data structures and OS systems coding", type: "technical" },
      { name: "Systems & Security Deep Dive", desc: "Kernel drivers, threat detection algorithms, and concurrency", type: "technical" },
      { name: "Cloud Architecture", desc: "Scaling telemetry pipelines handling trillions of security events daily", type: "system_design" },
      { name: "Values & Leadership", desc: "Mission-driven focus on stopping enterprise breaches", type: "hr" },
    ],
    topSkillsNeeded: ["Operating Systems & Kernel Internals", "C++ / Go", "Threat Detection & SIEM", "High-Throughput Streaming"],
    relatedCompanyIds: ["palo-alto-networks", "cloudflare", "cisco", "microsoft"],
    mentorCommentary: {
      nova: "CrowdStrike Falcon processes over 1 trillion security events per day. It is one of the most advanced real-time cloud security engines.",
      athena: "Demonstrate deep knowledge of OS telemetry, event streaming with Kafka, and low-level kernel event monitoring.",
      byte: "Kernel programming requires absolute perfection. A single unhandled null pointer crashes the entire host operating system.",
      raven: "Adversaries are relentless. If your security telemetry pipeline drops packets under load, you've failed the mission.",
      atlas: "CrowdStrike pioneered remote-first high-impact cybersecurity engineering. An extraordinary brand for security professionals.",
      sage: "Our roadmap will train you on OS internals, telemetry streaming architectures, and advanced vulnerability response.",
    },
  },
];

// Helper to quickly look up a verified company
export function getVerifiedCompanyById(id: string): VerifiedCompany | undefined {
  return VERIFIED_COMPANIES.find((c) => c.id === id);
}
