import { RoleDetails } from "@/types";

export const ROLE_CATALOG: RoleDetails[] = [
  {
    id: "software-engineer",
    name: "Software Engineer",
    icon: "laptop",
    description: "Architect scalable software products, core engineering systems, and maintainable services",
    salaryRange: "₹8L–45L",
    topCompanies: ["Google", "Microsoft", "Amazon", "Adobe"],
    demandLevel: 5,
    difficultyLevel: 4,
    badge: {
      text: "Highest Hiring",
      type: "hiring",
      icon: "briefcase",
    },
    estimatedMonths: 8,
    competition: 4,
    growth: "Excellent",
    topSkills: ["Java / C++", "DSA", "System Design", "OOP", "Git"],
    matchKeywords: ["java", "c++", "dsa", "algorithms", "problem solving", "sde", "swe", "software engineer"],
    autocompleteTokens: [
      "Software Engineer",
      "Software Developer",
      "SDE 1",
      "Core Software Engineer",
      "Product Engineer",
    ],
    mentorTip: "Solid grasp of data structures and clean code modularity will unlock tier-1 interviews.",
  },
  {
    id: "backend-developer",
    name: "Backend Developer",
    icon: "server",
    description: "Design resilient high-throughput microservices, caching layers, and secure database schemas",
    salaryRange: "₹8L–42L",
    topCompanies: ["Uber", "Amazon", "Netflix", "Atlassian"],
    demandLevel: 5,
    difficultyLevel: 4,
    badge: {
      text: "Highest Hiring",
      type: "hiring",
      icon: "briefcase",
    },
    estimatedMonths: 8,
    competition: 4,
    growth: "Excellent",
    topSkills: ["Java / Go", "Spring Boot / Node", "PostgreSQL", "Docker", "REST & gRPC"],
    matchKeywords: ["backend", "api", "spring boot", "node.js", "express", "sql", "microservices", ".net", "django"],
    autocompleteTokens: [
      "Backend Developer",
      "Backend Engineer",
      "API Engineer",
      "Server Engineer",
      "Distributed Systems Engineer",
    ],
    mentorTip: "Master transaction ACID boundaries, database indexing, and async queuing trade-offs.",
  },
  {
    id: "frontend-developer",
    name: "Frontend Developer",
    icon: "layout",
    description: "Craft pixel-perfect, accessible, and ultra-responsive interactive client applications",
    salaryRange: "₹6L–32L",
    topCompanies: ["Airbnb", "Cred", "Vercel", "Canva"],
    demandLevel: 4,
    difficultyLevel: 3,
    badge: {
      text: "Beginner Friendly",
      type: "beginner",
      icon: "sparkles",
    },
    estimatedMonths: 5,
    competition: 4,
    growth: "High",
    topSkills: ["React", "TypeScript", "Tailwind CSS", "Web Performance", "State Management"],
    matchKeywords: ["react", "frontend", "ui", "css", "html", "javascript", "vue", "angular", "web"],
    autocompleteTokens: [
      "Frontend Developer",
      "Frontend Engineer",
      "UI Engineer",
      "Client Web Developer",
    ],
    mentorTip: "Focus heavily on rendering performance, Web Vitals, and responsive CSS architecture.",
  },
  {
    id: "full-stack-engineer",
    name: "Full Stack Engineer",
    icon: "layers",
    description: "Build end-to-end web applications bridging responsive client UI and high-throughput backend APIs",
    salaryRange: "₹7L–38L",
    topCompanies: ["Razorpay", "Swiggy", "Meta", "Stripe"],
    demandLevel: 5,
    difficultyLevel: 3,
    badge: {
      text: "Trending",
      type: "trending",
      icon: "flame",
    },
    estimatedMonths: 6,
    competition: 4,
    growth: "High",
    topSkills: ["React", "Next.js", "Node.js", "PostgreSQL", "REST APIs"],
    matchKeywords: ["react", "next.js", "javascript", "typescript", "node.js", "full stack", "mern"],
    autocompleteTokens: [
      "Full Stack Engineer",
      "Full Stack Developer",
      "MERN Stack Developer",
      "Web Developer",
    ],
    mentorTip: "Demonstrating a deployed production full-stack project with real users beats 10 certificates.",
  },
  {
    id: "ai-engineer",
    name: "AI Engineer",
    icon: "bot",
    description: "Build LLM applications, RAG search pipelines, agentic workflows, and fine-tune models",
    salaryRange: "₹12L–60L",
    topCompanies: ["OpenAI", "Anthropic", "Google DeepMind", "Microsoft"],
    demandLevel: 5,
    difficultyLevel: 5,
    badge: {
      text: "AI Boom",
      type: "ai",
      icon: "bot",
    },
    estimatedMonths: 9,
    competition: 4,
    growth: "Exponential",
    topSkills: ["Python", "LangChain", "Vector DBs", "PyTorch", "Prompt Engineering"],
    matchKeywords: ["ai", "python", "llm", "genai", "prompt engineering", "rag", "agents", "langchain", "openai"],
    autocompleteTokens: [
      "AI Engineer",
      "Generative AI Engineer",
      "LLM Application Engineer",
      "Agentic AI Developer",
    ],
    mentorTip: "The market seeks builders who connect LLMs with real databases, tools, and evaluation benchmarks.",
  },
  {
    id: "machine-learning-engineer",
    name: "Machine Learning Engineer",
    icon: "brain",
    description: "Train, evaluate, and productionize predictive models, computer vision, and NLP pipelines",
    salaryRange: "₹10L–50L",
    topCompanies: ["NVIDIA", "Meta", "Apple", "Databricks"],
    demandLevel: 5,
    difficultyLevel: 5,
    badge: {
      text: "Fast Growing",
      type: "growth",
      icon: "trending-up",
    },
    estimatedMonths: 10,
    competition: 4,
    growth: "Exponential",
    topSkills: ["Python", "TensorFlow / PyTorch", "Scikit-Learn", "MLOps", "Statistics"],
    matchKeywords: ["ml", "machine learning", "deep learning", "neural networks", "python", "tensorflow", "pytorch"],
    autocompleteTokens: [
      "Machine Learning Engineer",
      "ML Engineer",
      "Deep Learning Engineer",
      "Computer Vision Specialist",
      "NLP Engineer",
    ],
    mentorTip: "Mathematical grounding in linear algebra and loss functions will set you apart from tutorial coders.",
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    icon: "bar-chart-3",
    description: "Uncover actionable business patterns and predictive insights from complex multi-source datasets",
    salaryRange: "₹8L–36L",
    topCompanies: ["Walmart Labs", "LinkedIn", "JPMorgan", "Target"],
    demandLevel: 4,
    difficultyLevel: 4,
    badge: {
      text: "Trending",
      type: "trending",
      icon: "flame",
    },
    estimatedMonths: 7,
    competition: 4,
    growth: "High",
    topSkills: ["Python / R", "SQL", "Pandas", "Hypothesis Testing", "Data Visualization"],
    matchKeywords: ["data", "sql", "analytics", "statistics", "python", "pandas", "data science"],
    autocompleteTokens: [
      "Data Scientist",
      "Data Analyst",
      "Applied Scientist",
      "Business Intelligence Analyst",
    ],
    mentorTip: "Communicating business value through storytelling matters just as much as model accuracy.",
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    icon: "git-branch",
    description: "Engineer CI/CD pipelines, container orchestration, infrastructure as code, and site reliability",
    salaryRange: "₹8L–38L",
    topCompanies: ["Red Hat", "GitLab", "Atlassian", "Salesforce"],
    demandLevel: 5,
    difficultyLevel: 4,
    badge: {
      text: "Fast Growing",
      type: "growth",
      icon: "trending-up",
    },
    estimatedMonths: 7,
    competition: 3,
    growth: "Excellent",
    topSkills: ["Docker & Kubernetes", "CI/CD (GitHub Actions)", "Terraform", "Linux & Bash", "Prometheus"],
    matchKeywords: ["devops", "docker", "kubernetes", "k8s", "ci/cd", "jenkins", "terraform", "sre", "linux"],
    autocompleteTokens: [
      "DevOps Engineer",
      "Site Reliability Engineer (SRE)",
      "Platform Engineer",
      "Build & Release Engineer",
    ],
    mentorTip: "Production outages don't care about excuses—infrastructure as code makes reliability repeatable.",
  },
  {
    id: "cloud-engineer",
    name: "Cloud Engineer",
    icon: "cloud",
    description: "Design cloud architectures, serverless backends, multi-region failovers, and cloud security",
    salaryRange: "₹9L–42L",
    topCompanies: ["AWS", "Microsoft Azure", "Google Cloud", "Oracle Cloud"],
    demandLevel: 5,
    difficultyLevel: 4,
    badge: {
      text: "Highest Hiring",
      type: "hiring",
      icon: "briefcase",
    },
    estimatedMonths: 7,
    competition: 3,
    growth: "Excellent",
    topSkills: ["AWS / Azure / GCP", "Serverless Architecture", "Cloud Security & IAM", "Terraform", "Networking"],
    matchKeywords: ["cloud", "aws", "azure", "gcp", "cloud engineer", "serverless", "cloud architecture", "iam"],
    autocompleteTokens: [
      "Cloud Engineer",
      "Cloud Architect",
      "AWS Solutions Architect",
      "Cloud Infrastructure Engineer",
    ],
    mentorTip: "Earning an AWS Solutions Architect or Azure Administrator certification provides strong initial credibility.",
  },
  {
    id: "cyber-security-analyst",
    name: "Cyber Security Analyst",
    icon: "shield-check",
    description: "Protect systems, conduct penetration testing, and audit software vulnerability defenses",
    salaryRange: "₹7L–35L",
    topCompanies: ["Palo Alto Networks", "CrowdStrike", "Cisco", "Cloudflare"],
    demandLevel: 5,
    difficultyLevel: 4,
    badge: {
      text: "Fast Growing",
      type: "growth",
      icon: "trending-up",
    },
    estimatedMonths: 8,
    competition: 3,
    growth: "Excellent",
    topSkills: ["Network Security", "Ethical Hacking", "Cryptography", "Linux", "SIEM"],
    matchKeywords: ["security", "cyber", "penetration testing", "networking", "cryptography", "infosec", "soc"],
    autocompleteTokens: [
      "Cyber Security Analyst",
      "Security Engineer",
      "Penetration Tester",
      "Information Security Officer",
      "SOC Analyst",
    ],
    mentorTip: "Hands-on experience with TryHackMe or CTF challenges gives instant credibility in interviews.",
  },
  {
    id: "android-engineer",
    name: "Android Engineer",
    icon: "smartphone",
    description: "Build smooth native mobile applications with Kotlin, Jetpack Compose, and modern Android architecture",
    salaryRange: "₹6L–30L",
    topCompanies: ["Zomato", "Flipkart", "PhonePe", "Google"],
    demandLevel: 4,
    difficultyLevel: 3,
    badge: {
      text: "Beginner Friendly",
      type: "beginner",
      icon: "sparkles",
    },
    estimatedMonths: 6,
    competition: 3,
    growth: "High",
    topSkills: ["Kotlin", "Jetpack Compose", "Coroutines", "Android SDK", "MVVM"],
    matchKeywords: ["android", "kotlin", "mobile", "jetpack", "apps", "flutter", "react native"],
    autocompleteTokens: [
      "Android Engineer",
      "Android Developer",
      "Mobile Application Developer",
      "Kotlin Developer",
    ],
    mentorTip: "Publishing even one clean app with 100+ downloads on the Play Store puts you in the top 5% of freshers.",
  },
  {
    id: "ios-engineer",
    name: "iOS Engineer",
    icon: "smartphone",
    description: "Craft fluid Apple ecosystem applications using modern Swift, SwiftUI, and design human guidelines",
    salaryRange: "₹7L–36L",
    topCompanies: ["Apple", "Uber", "Spotify", "Robinhood"],
    demandLevel: 4,
    difficultyLevel: 4,
    badge: {
      text: "Highest Hiring",
      type: "hiring",
      icon: "briefcase",
    },
    estimatedMonths: 7,
    competition: 3,
    growth: "High",
    topSkills: ["Swift", "SwiftUI", "Combine", "iOS Architecture", "XCode"],
    matchKeywords: ["ios", "swift", "apple", "swiftui", "mobile", "flutter", "react native"],
    autocompleteTokens: [
      "iOS Engineer",
      "iOS Developer",
      "Apple Ecosystem Developer",
      "Swift Specialist",
    ],
    mentorTip: "Focus on buttery 120Hz smooth transitions, HIG guidelines, and asynchronous concurrency.",
  },
  {
    id: "ui-ux-designer",
    name: "UI/UX Designer",
    icon: "sparkles",
    description: "Create design systems, interactive prototypes, user journeys, and modern SaaS product interfaces",
    salaryRange: "₹6L–30L",
    topCompanies: ["Figma", "Notion", "Linear", "Airbnb"],
    demandLevel: 4,
    difficultyLevel: 3,
    badge: {
      text: "Beginner Friendly",
      type: "beginner",
      icon: "sparkles",
    },
    estimatedMonths: 5,
    competition: 4,
    growth: "High",
    topSkills: ["Figma", "Design Systems", "User Research", "Wireframing", "Prototyping"],
    matchKeywords: ["design", "ui", "ux", "figma", "product design", "prototyping", "wireframes"],
    autocompleteTokens: [
      "UI/UX Designer",
      "Product Designer",
      "Interaction Designer",
      "User Experience Researcher",
    ],
    mentorTip: "Present case studies emphasizing the 'Why' behind design decisions and usability test metrics.",
  },
  {
    id: "game-developer",
    name: "Game Developer",
    icon: "gamepad-2",
    description: "Engineer interactive gameplay, physics simulations, 3D graphics rendering, and multiplayer engines",
    salaryRange: "₹6L–35L",
    topCompanies: ["Electronic Arts", "Ubisoft", "Rockstar Games", "Epic Games"],
    demandLevel: 4,
    difficultyLevel: 5,
    badge: {
      text: "Fast Growing",
      type: "growth",
      icon: "trending-up",
    },
    estimatedMonths: 9,
    competition: 4,
    growth: "High",
    topSkills: ["C++ / C#", "Unity / Unreal Engine", "3D Math & Physics", "Shaders & Graphics", "Game Mechanics"],
    matchKeywords: ["game", "unity", "unreal", "game developer", "godot", "blender", "c++", "c#", "graphics", "shaders"],
    autocompleteTokens: [
      "Game Developer",
      "Unity Developer",
      "Unreal Engine Developer",
      "Gameplay Programmer",
      "Graphics Programmer",
    ],
    mentorTip: "Complete a playable game jam project with polished physics and mechanics to showcase in your portfolio.",
  },
];

export const ROLE_NAMES = ROLE_CATALOG.map((role) => role.name);
